-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 25, 2018 at 10:04 PM
-- Server version: 10.1.29-MariaDB
-- PHP Version: 7.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ed01-cms`
--

-- --------------------------------------------------------

--
-- Table structure for table `cms_categories`
--

CREATE TABLE `cms_categories` (
  `cat_id` int(3) NOT NULL,
  `cat_title` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `cms_categories`
--

INSERT INTO `cms_categories` (`cat_id`, `cat_title`) VALUES
(51, 'Stories'),
(52, 'Dice Shooting'),
(53, 'Strategies'),
(58, 'Money Mgmt'),
(59, 'Comps'),
(66, 'Vegas Deals'),
(69, 'Good Eats'),
(71, 'Sports Books'),
(72, 'Travel'),
(73, 'Shows'),
(74, 'Other Games');

-- --------------------------------------------------------

--
-- Table structure for table `cms_comments`
--

CREATE TABLE `cms_comments` (
  `comment_id` int(3) NOT NULL,
  `comment_post_id` int(3) NOT NULL,
  `comment_author` varchar(50) NOT NULL,
  `comment_content` text NOT NULL,
  `comment_status` varchar(50) NOT NULL,
  `comment_date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `cms_comments`
--

INSERT INTO `cms_comments` (`comment_id`, `comment_post_id`, `comment_author`, `comment_content`, `comment_status`, `comment_date`) VALUES
(1, 37, 'partygirl', '<p>Royal flush golden nugget all in bankroll caesar\'s palace stratosphere! Betting limits the district two pair flamingo hotel? Tapped out fremont street breaking even. Bust fruit loop pot the district haze ante; blind the chapel of love shooter city center? </p>', 'like', '2015-09-13 15:55:27'),
(2, 34, 'samuel', '<p>From \'Jackie Brown\': My money\'s in that office, right? If she start giving me some bullshit about it ain\'t there, and we got to go someplace else and get it, I\'m gonna shoot you in the head then and there.</p>', 'like', '2015-09-13 19:32:23'),
(3, 36, 'samuel', '<p>I am even happier that I found Samuel L. Ipsum: Look, just because I don\'t be givin\' no man a foot massage don\'t make it right for Marsellus to throw Antwone into a glass ...</p>', 'dislike', '2015-09-13 16:06:07'),
(10, 33, 'samuel', '<p>Well, the way they make shows is, they make one show. That show\'s called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they\'re going to make more shows. Some pilots get picked and become television programs. Some don\'t, become nothing.</p>', 'like', '2015-09-13 19:38:34'),
(11, 35, 'samuel', '<p>From \'Jackie Brown\': Now that there is the Tec-9, a crappy spray gun from South Miami. This gun is advertised as the most popular gun in American crime. Do you believe that shit? It actually says that in the little book that comes with it: the most popular gun in American crime. Like they\'re actually proud of that shit.</p>', 'dislike', '2015-09-13 19:41:38'),
(21, 35, 'elvis', 'Uh huh!?', 'like', '2015-09-15 16:53:36'),
(29, 56, 'samuel', 'The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother\'s keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy my brothers. And you will know my name is the Lord when I lay my vengeance upon thee.', 'dislike', '2015-09-16 15:15:12'),
(33, 71, 'elvis', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur volutpat, leo nec laoreet vehicula, lectus ipsum porta nibh, eget malesuada augue purus ut ipsum. Sed molestie sit amet diam eget.\r\n', 'dislike', '2015-09-16 20:51:33'),
(36, 71, 'tiffany', 'Cupcake ipsum dolor sit amet jelly-o gingerbread pastry. DragÃ©e icing marzipan jelly-o cookie toffee candy canes topping wafer. Halvah liquorice cake cookie gummies jelly-o.', 'like', '2015-09-17 18:27:29'),
(37, 70, 'tiffany', 'Cupcake ipsum dolor sit amet jelly-o gingerbread pastry. DragÃ©e icing marzipan jelly-o cookie toffee candy canes topping wafer. Halvah liquorice cake cookie gummies jelly-o.', 'like', '2015-09-17 18:29:39'),
(40, 68, 'elvis', 'Bayou fais do do downtown bourre praline etoufee fishing smoked sausage. Jambalaya andouille Fauxcheaux hot sauce praline tasso. Macque choux Fauxcheaux boucherie sac a lait catahoula okra gumbo Fauxcheaux. \r\n', 'dislike', '2015-09-17 18:33:30'),
(45, 72, 'elvis', 'Say what?', 'like', '2015-09-17 20:04:43'),
(46, 72, 'eleanor', 'La grande ambition des femmes est d\'inspirer l\'amour.', 'like', '2015-09-17 20:11:53'),
(48, 70, 'test66', 'Quare hoc quidem praeceptum, cuiuscumque est, ad tollendam amicitiam valet.', 'like', '2015-09-18 18:47:28'),
(51, 66, 'blofeld', 'Comment 1', 'like', '2015-09-18 20:40:46'),
(57, 74, 'highroller', 'Get your lady friend to blow on them!', 'like', '2015-09-18 21:31:31'),
(58, 66, 'blofeld', 'You only live twice, Mr. Bond!', 'like', '2015-09-18 22:04:02'),
(60, 66, 'blofeld', 'This is the price of failure, Mr. Bond.', 'dislike', '2015-09-18 22:06:16'),
(61, 66, 'blofeld', 'Comment 2', 'dislike', '2015-09-18 22:06:35'),
(62, 66, 'blofeld', 'Comment 3', 'dislike', '2015-09-18 22:06:47'),
(63, 35, 'highroller', 'High roller town square feeling lucky house edge tease swim-up blackjack! Unlv blind the joint? The luxor hard rock hotel lax the chapel of love pass! Pit the strip flamingo hotel fifth street odds shuffle, bluff fold vdara chateau.', 'like', '2015-09-18 22:10:33'),
(64, 35, 'highroller', 'The district bars sixth street dayclubs draw dice, betting limits feeling lucky tease cosmopolitan! Tapped out bankroll the mirage the chandelier fold golden nugget.', 'like', '2015-09-18 22:11:01'),
(67, 99, 'highroller', 'Glitter gluch baccarat chips golden nugget whale blackjack fremont street: hit unlv insurance loose tao fashion show mall!', 'dislike', '2015-09-18 22:32:19'),
(68, 99, 'elvis', 'ull house convention center bars new york, new york zappos caesar\'s palace! Body english glitter gluch the pairs fifth street flamingo hotel, shops at crystals fremont street comps aria.', 'like', '2015-09-18 22:32:43'),
(71, 100, 'elvis', 'The chapel of love the district flamingo hotel city center dice double down?', 'like', '2015-09-18 22:34:06'),
(72, 101, 'eleanor', 'Margaritaville hit straight town square payoff top of the world edge capriotti\'s! Hit score bars draw lock all in! Zappos all in swim-up blackjack top of the world card counting; bankroll loose score bars! The mirage the luxor fremont street nightclubs pit boss high roller; hand haze bars pass sin city.', 'dislike', '2015-09-18 22:34:47'),
(73, 102, 'doctordice', 'Fruit loop pit royal flush tao comps town square shooter; fremont street zappos straight two pair swim-up blackjack.', 'like', '2015-09-18 22:35:39'),
(75, 102, 'test66', 'Body english sin city fifth street house edge full house pass blind, insurance hit the luxor the chandelier the joint!', 'like', '2015-09-18 22:36:43'),
(76, 103, 'casinoowner', 'Full house hard rock hotel veer towers dice probability; shooter house edge payoff double down.', 'dislike', '2015-09-18 22:37:22'),
(78, 105, 'strategist', 'The pairs bars pit boss bankroll the district stratosphere flush, price push house edge unlv lock edge! Card counting capriotti\'s bankroll hit the mgm grand lax?', 'like', '2015-09-18 22:39:08'),
(79, 105, 'elvis', 'Oh yeah!', 'like', '2015-09-18 22:39:23'),
(80, 105, 'elvis', 'Oh yeah!', 'like', '2015-09-18 22:43:32'),
(81, 99, 'highroller', 'Exactly!', 'like', '2015-09-18 23:27:38'),
(82, 107, 'partygirl', 'Probability fruit loop the luxor royal flush new york, new york straight hard rock hotel veer towers. Push hard rock hotel vdara tao dealer, lock aria hit lax. ', 'like', '2015-09-18 23:35:18'),
(83, 67, 'partygirl', 'New york, new york dice fruit loop double down chips miracle mile shops bankroll. The district the palms fashion show mall the chapel of love.', 'like', '2015-09-18 23:35:39');

-- --------------------------------------------------------

--
-- Table structure for table `cms_posts`
--

CREATE TABLE `cms_posts` (
  `post_id` int(3) NOT NULL,
  `post_cat_id` int(3) NOT NULL,
  `post_title` varchar(100) NOT NULL,
  `post_author` varchar(50) NOT NULL,
  `post_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `post_image` varchar(50) NOT NULL DEFAULT 'xyz.png',
  `post_content` text NOT NULL,
  `post_tags` varchar(100) NOT NULL,
  `post_status` varchar(100) NOT NULL,
  `post_views_count` int(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `cms_posts`
--

INSERT INTO `cms_posts` (`post_id`, `post_cat_id`, `post_title`, `post_author`, `post_date`, `post_image`, `post_content`, `post_tags`, `post_status`, `post_views_count`) VALUES
(32, 52, 'How to hold dice as you toss', 'dicemaster', '2015-09-14 03:44:34', 'image4.png', '<p>Chateau comps unlv loose vegas givecamp hard rock hotel fold? Shooter veer towers lounges comps blackjack shops at crystals flush; insurance double down payoff all in miracle mile shops mandalay bay! Ante lock vegas givecamp mandalay bay dayclubs city center! Rack ante sin city fashion show mall blackjack the strip town square spaghetti bowl. Full house the chapel of love flamingo hotel zappos vegas givecamp lax. City center golden nugget shops at crystals fruit loop dealer new york, new york loose. </p>\r\n<p>Insurance high roller blackjack hand stratosphere the chapel of love the venetian, glitter gluch two pair score full house straight stand. Shops at crystals flush payoff all in loose edge, exposure royal flush straight fremont street check! Cosmopolitan city center double down miracle mile shops the luxor shops at crystals, the chapel of love sin city veer towers chateau baccarat. Betting limits blind baccarat high roller the mirage house edge golden nugget aria? Probability cosmopolitan bluff top of the world fruit loop, swim-up blackjack treasure island sin city all in. Bars double down royal flush tapped out fruit loop lounges, baccarat fold dayclubs naked city. </p>\r\n<p>New york, new york fremont street sin city shooter chateau vegas givecamp baccarat, the venetian edge stand royal flush bust? Hard rock hotel insurance payoff nightclubs shuffle dayclubs the joint, the venetian push lounges veer towers top of the world. Straight score the pairs unlv flush body english push: mandalay bay pot hit all in the palms miracle mile shops? Pass miracle mile shops the mirage convention center blackjack the pairs; two pair bust house edge insurance high roller. Check caesar\'s palace pit nightclubs sin city edge hard rock hotel; aria loose parlay capriotti\'s card counting. Treasure island bankroll ante feeling lucky swim-up blackjack parlay the chandelier: cosmopolitan shooter dealer nightclubs aria fruit loop? </p>', 'craps dice vegas roll hold bounce table', 'Published', 20),
(33, 53, 'How does off-and-on work on come-bets?', 'doctordice', '2015-09-13 08:51:24', 'image5.png', '<p>Haze naked city spaghetti bowl the excalibur comps: the chapel of love exposure flush probability. The joint blackjack aria push the pairs sixth street the venetian zappos. Straight lounges top of the world insurance the strip! Card counting convention center chips the chapel of love bankroll, price pit the district parlay? </p>\r\n<p>The venetian margaritaville fremont street fashion show mall hit fifth street the strip swim-up blackjack? Flamingo hotel card counting nightclubs spaghetti bowl fifth street caesar\'s palace rack hand! Two pair flamingo hotel hit? Vegas givecamp lock nightclubs bluff golden nugget the joint, double down tease top of the world the excalibur. </p>\r\n<p>Pot hard rock hotel the chapel of love! Bust loose town square rack the luxor wildcard shops at crystals the palms. The chandelier dealer parlay margaritaville royal flush pass top of the world. Flamingo hotel blackjack nightclubs top of the world treasure island shops at crystals? </p>', 'craps strategies bets dealers come odds', 'Published', 27),
(34, 58, 'How does the Kelly Criterion apply to shooting craps?', 'highroller', '2015-09-13 08:47:07', 'image3.png', '<p>Tease sixth street miracle mile shops breaking even swim-up blackjack the joint insurance, feeling lucky new york, new york lounges the district loose margaritaville. Bust blind flamingo hotel sixth street flush fifth street check pit: swim-up blackjack price fremont street the district body english two pair. Payoff feeling lucky check top of the world caesar\'s palace pass: veer towers cosmopolitan full house baccarat? City center baccarat hand all in veer towers; bust caesar\'s palace dealer lock. All in aria bars feeling lucky chateau shops at crystals; haze royal flush draw the pairs. The chandelier parlay baccarat the district bars the mirage: straight tapped out betting limits tao lock; sin city nightclubs naked city breaking even. Fruit loop the strip cosmopolitan fremont street royal flush parlay; blind push straight insurance vegas givecamp; golden nugget feeling lucky bars dayclubs pass! Straight chips lock chateau push caesar\'s palace edge: bust house edge vdara loose shuffle! </p>\r\n<p>The mgm grand top of the world pot blind two pair hand: vdara nightclubs tapped out draw shops at crystals, card counting betting limits dice probability? Price bellagio two pair loose top of the world: swim-up blackjack wildcard shooter payoff. Cosmopolitan insurance the excalibur comps the mgm grand straight; sin city probability dice capriotti\'s aria? Glitter gluch edge lock cosmopolitan card counting margaritaville loose: city center haze fifth street miracle mile shops odds zappos! Glitter gluch ante wildcard flush house edge mandalay bay: new york, new york fashion show mall chips the pairs draw. Pass fifth street new york, new york pot double down body english cosmopolitan: all in rack price town square odds! Two pair pit boss the palms loose lounges shuffle bust: flush chateau sixth street cosmopolitan comps! The excalibur body english shops at crystals insurance whale lounges, parlay probability city center bluff high roller; pit draw treasure island ante! </p>', 'bets strategies money management kelly criterion', 'Published', 15),
(35, 59, 'Comps: The secret behind those freebies', 'highroller', '2015-09-13 08:49:37', 'image6.png', '<p>Sin city pass shops at crystals hard rock hotel push shuffle: hand loose veer towers chateau! Full house tease draw nightclubs. Golden nugget haze capriotti\'s draw? Mandalay bay the palms vdara straight bellagio: the venetian baccarat edge convention center. </p>\r\n<p>Shops at crystals tease unlv hard rock hotel shooter parlay: bars comps city center flush? Probability hard rock hotel ante fashion show mall haze? Comps high roller the excalibur chateau bars blackjack, breaking even hand odds dealer! Fold the joint payoff chateau? </p>\r\n<p>Baccarat bellagio the district chips price shooter the strip. Probability the palms straight the excalibur. Fold shooter stratosphere draw miracle mile shops. Parlay full house glitter gluch royal flush chateau dealer? </p>\r\n<p>Stratosphere straight pit boss swim-up blackjack golden nugget flamingo hotel? Cosmopolitan the palms odds stand shuffle; town square sin city bellagio comps? Hit haze shooter. Vdara price treasure island haze aria the district hit the palms! </p>\r\n<p>Town square fremont street feeling lucky city center stand! Rack shooter pit boss two pair lock town square? Tease blind lock comps the palms wildcard haze new york, new york! Body english vdara town square convention center edge chateau, the excalibur draw aria chips? </p>', 'comps deals casinos free club cards food shows', 'Published', 21),
(36, 51, 'Glad I found vegasipsum.com!', 'casinoowner', '2015-09-13 21:26:59', 'image7.png', '<p>Odds whale rack edge body english exposure shooter, hard rock hotel fremont street new york, new york loose unlv city center? Golden nugget the palms vdara lock double down tao; top of the world the luxor ante aria? Draw hard rock hotel pot lounges fremont street: shops at crystals chips vegas givecamp shooter! Straight rack miracle mile shops edge draw: tao house edge the excalibur lax? Haze convention center the chapel of love pit chateau flush: edge royal flush shuffle the mgm grand bars? Check miracle mile shops payoff glitter gluch cosmopolitan: margaritaville chips the pairs body english. </p>', 'lorem ipsum vegas filler text', 'Published', 16),
(37, 74, 'Nightclub Scene', 'partygirl', '2015-09-13 08:58:57', 'image2.png', '<p>Convention center sixth street body english cosmopolitan the excalibur new york, new york. Straight the luxor chateau. Veer towers vdara aria shops at crystals city center mandalay bay tao body english! Straight dayclubs pit boss tao. </p>\r\n<p>Haze glitter gluch two pair bluff check double down, loose vegas givecamp bars vdara? Full house pit boss score! Push pass naked city vdara! The chapel of love sixth street town square dice unlv? </p>\r\n<p>Chips royal flush shooter zappos straight. Fold new york, new york shooter price zappos blackjack the district cosmopolitan? Flamingo hotel shuffle golden nugget aria haze glitter gluch: two pair bellagio the chapel of love fifth street! The mirage the luxor bars score margaritaville dayclubs. </p>\r\n<p>Dealer price vdara hand check bars comps? Odds vegas givecamp city center double down fruit loop? Rack fold pass bluff haze chateau: whale dealer cosmopolitan treasure island? Fashion show mall stand betting limits aria fremont street pot vegas givecamp? </p>\r\n<p>Haze caesar\'s palace the district odds high roller! Parlay feeling lucky hit high roller? Margaritaville cosmopolitan pot? Chateau straight wildcard fremont street the district margaritaville: spaghetti bowl lax hand bankroll. </p>\r\n<p>Aria insurance tapped out nightclubs the strip. Push the chandelier stratosphere betting limits whale house edge? Unlv lounges nightclubs hand payoff? Shooter fremont street margaritaville town square full house; zappos the palms stand house edge. </p>', 'clubs night party dance music dj alcohol celebs', 'Published', 20),
(38, 53, 'The best proposition bets', 'strategist', '2015-09-13 09:03:32', 'image1.png', '<p>Dice breaking even high roller. Payoff score dealer baccarat! Insurance the strip odds the mirage shuffle the chandelier rack pass. New york, new york capriotti\'s double down dealer pot two pair pass spaghetti bowl! </p>\r\n<p>Blind card counting shops at crystals high roller draw margaritaville aria. Pass capriotti\'s stand. Straight margaritaville the mirage tease glitter gluch the venetian? The district sin city full house lounges the chapel of love flamingo hotel probability loose. </p>\r\n<p>Stratosphere shooter insurance bankroll aria dealer glitter gluch. Straight dice bankroll new york, new york treasure island; the district parlay comps price! Push the joint new york, new york two pair lock insurance pit the palms! Price hand lounges comps the joint bust? </p>\r\n<p>Flamingo hotel hand hard rock hotel bankroll naked city, spaghetti bowl the mirage pot exposure. Body english the strip hand dayclubs tao. Glitter gluch bars pit boss draw straight: shooter baccarat rack fruit loop? Chateau capriotti\'s parlay hard rock hotel cosmopolitan feeling lucky: stratosphere lock the joint royal flush! </p>', 'dice craps bets props strategies hardways yo eleven snake eyes boxcars', 'Published', 15),
(39, 51, 'Gluttony Greed Lust Sloth Wrath Envy Pride', 'pahrump', '2015-09-14 04:01:00', 'image8.png', '<p>Two pair town square pass pit boss the luxor chips? All in card counting dice? Tao high roller probability golden nugget exposure lounges house edge the pairs. Glitter gluch swim-up blackjack lock shuffle chateau hit unlv the chandelier. </p>\r\n<p>Push draw all in spaghetti bowl blind: the mgm grand hard rock hotel naked city comps? Double down score ante unlv! Shuffle card counting pass flamingo hotel sin city treasure island! Lax blackjack high roller the chapel of love fashion show mall unlv: miracle mile shops naked city bust full house. </p>\r\n<p>Chateau the strip stand double down vdara vegas givecamp dealer? Whale new york, new york stand ante sixth street pit, shuffle aria convention center price? The excalibur double down spaghetti bowl? Pit city center the joint fifth street baccarat vdara card counting miracle mile shops. </p>', 'deadly sins hell evil devil damnation', 'Published', 13),
(41, 51, 'You only live twice, Mr. Bond', 'blofeld', '2015-09-16 02:52:10', 'image9.png', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut viverra in purus sit amet laoreet. Vivamus luctus fringilla nisi, eget tempor mauris iaculis vitae. Suspendisse non dui sit amet lacus scelerisque aliquam ut id ipsum. Quisque aliquam ornare purus, eu hendrerit purus. Sed auctor diam a quam iaculis hendrerit. Ut suscipit imperdiet arcu, nec molestie lectus iaculis ut. Nam tortor velit, rutrum quis interdum in, dignissim sit amet sem. Nullam quis sagittis lacus, nec tempus turpis. Vivamus efficitur euismod accumsan. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae</p>\r\n', 'bond 007 diamonds blofeld spectre', 'Draft', 15),
(42, 52, 'How to hold dice as you toss', 'dicemaster', '2015-09-16 02:57:19', 'image4.png', '<p>Chateau comps unlv loose vegas givecamp hard rock hotel fold? Shooter veer towers lounges comps blackjack shops at crystals flush; insurance double down payoff all in miracle mile shops mandalay bay! Ante lock vegas givecamp mandalay bay dayclubs city center! Rack ante sin city fashion show mall blackjack the strip town square spaghetti bowl. Full house the chapel of love flamingo hotel zappos vegas givecamp lax. City center golden nugget shops at crystals fruit loop dealer new york, new york loose. </p>\r\n<p>Insurance high roller blackjack hand stratosphere the chapel of love the venetian, glitter gluch two pair score full house straight stand. Shops at crystals flush payoff all in loose edge, exposure royal flush straight fremont street check! Cosmopolitan city center double down miracle mile shops the luxor shops at crystals, the chapel of love sin city veer towers chateau baccarat. Betting limits blind baccarat high roller the mirage house edge golden nugget aria? Probability cosmopolitan bluff top of the world fruit loop, swim-up blackjack treasure island sin city all in. Bars double down royal flush tapped out fruit loop lounges, baccarat fold dayclubs naked city. </p>\r\n<p>New york, new york fremont street sin city shooter chateau vegas givecamp baccarat, the venetian edge stand royal flush bust? Hard rock hotel insurance payoff nightclubs shuffle dayclubs the joint, the venetian push lounges veer towers top of the world. Straight score the pairs unlv flush body english push: mandalay bay pot hit all in the palms miracle mile shops? Pass miracle mile shops the mirage convention center blackjack the pairs; two pair bust house edge insurance high roller. Check caesar\'s palace pit nightclubs sin city edge hard rock hotel; aria loose parlay capriotti\'s card counting. Treasure island bankroll ante feeling lucky swim-up blackjack parlay the chandelier: cosmopolitan shooter dealer nightclubs aria fruit loop? </p>', 'craps dice vegas roll hold bounce table', 'Published', 14),
(43, 51, 'Glad I found vegasipsum.com!', 'casinoowner', '2015-09-16 02:57:19', 'image7.png', '<p>Odds whale rack edge body english exposure shooter, hard rock hotel fremont street new york, new york loose unlv city center? Golden nugget the palms vdara lock double down tao; top of the world the luxor ante aria? Draw hard rock hotel pot lounges fremont street: shops at crystals chips vegas givecamp shooter! Straight rack miracle mile shops edge draw: tao house edge the excalibur lax? Haze convention center the chapel of love pit chateau flush: edge royal flush shuffle the mgm grand bars? Check miracle mile shops payoff glitter gluch cosmopolitan: margaritaville chips the pairs body english. </p>', 'lorem ipsum vegas filler text', 'Published', 20),
(44, 51, 'Gluttony Greed Lust Sloth Wrath Envy Pride', 'pahrump', '2015-09-16 02:57:19', 'image8.png', '<p>Two pair town square pass pit boss the luxor chips? All in card counting dice? Tao high roller probability golden nugget exposure lounges house edge the pairs. Glitter gluch swim-up blackjack lock shuffle chateau hit unlv the chandelier. </p>\r\n<p>Push draw all in spaghetti bowl blind: the mgm grand hard rock hotel naked city comps? Double down score ante unlv! Shuffle card counting pass flamingo hotel sin city treasure island! Lax blackjack high roller the chapel of love fashion show mall unlv: miracle mile shops naked city bust full house. </p>\r\n<p>Chateau the strip stand double down vdara vegas givecamp dealer? Whale new york, new york stand ante sixth street pit, shuffle aria convention center price? The excalibur double down spaghetti bowl? Pit city center the joint fifth street baccarat vdara card counting miracle mile shops. </p>', 'deadly sins hell evil devil damnation', 'Published', 27),
(45, 59, 'Comps: The secret behind those freebies', 'highroller', '2015-09-16 03:01:38', 'image6.png', '<p>Sin city pass shops at crystals hard rock hotel push shuffle: hand loose veer towers chateau! Full house tease draw nightclubs. Golden nugget haze capriotti\'s draw? Mandalay bay the palms vdara straight bellagio: the venetian baccarat edge convention center. </p>\r\n<p>Shops at crystals tease unlv hard rock hotel shooter parlay: bars comps city center flush? Probability hard rock hotel ante fashion show mall haze? Comps high roller the excalibur chateau bars blackjack, breaking even hand odds dealer! Fold the joint payoff chateau? </p>\r\n<p>Baccarat bellagio the district chips price shooter the strip. Probability the palms straight the excalibur. Fold shooter stratosphere draw miracle mile shops. Parlay full house glitter gluch royal flush chateau dealer? </p>\r\n<p>Stratosphere straight pit boss swim-up blackjack golden nugget flamingo hotel? Cosmopolitan the palms odds stand shuffle; town square sin city bellagio comps? Hit haze shooter. Vdara price treasure island haze aria the district hit the palms! </p>\r\n<p>Town square fremont street feeling lucky city center stand! Rack shooter pit boss two pair lock town square? Tease blind lock comps the palms wildcard haze new york, new york! Body english vdara town square convention center edge chateau, the excalibur draw aria chips? </p>', 'comps deals casinos free club cards food shows', 'Published', 12),
(46, 51, 'Glad I found vegasipsum.com!', 'casinoowner', '2015-09-16 03:01:38', 'image7.png', '<p>Odds whale rack edge body english exposure shooter, hard rock hotel fremont street new york, new york loose unlv city center? Golden nugget the palms vdara lock double down tao; top of the world the luxor ante aria? Draw hard rock hotel pot lounges fremont street: shops at crystals chips vegas givecamp shooter! Straight rack miracle mile shops edge draw: tao house edge the excalibur lax? Haze convention center the chapel of love pit chateau flush: edge royal flush shuffle the mgm grand bars? Check miracle mile shops payoff glitter gluch cosmopolitan: margaritaville chips the pairs body english. </p>', 'lorem ipsum vegas filler text', 'Published', 14),
(47, 73, 'Nightclub Scene', 'partygirl', '2015-09-16 03:01:38', 'image2.png', '<p>Convention center sixth street body english cosmopolitan the excalibur new york, new york. Straight the luxor chateau. Veer towers vdara aria shops at crystals city center mandalay bay tao body english! Straight dayclubs pit boss tao. </p>\r\n<p>Haze glitter gluch two pair bluff check double down, loose vegas givecamp bars vdara? Full house pit boss score! Push pass naked city vdara! The chapel of love sixth street town square dice unlv? </p>\r\n<p>Chips royal flush shooter zappos straight. Fold new york, new york shooter price zappos blackjack the district cosmopolitan? Flamingo hotel shuffle golden nugget aria haze glitter gluch: two pair bellagio the chapel of love fifth street! The mirage the luxor bars score margaritaville dayclubs. </p>\r\n<p>Dealer price vdara hand check bars comps? Odds vegas givecamp city center double down fruit loop? Rack fold pass bluff haze chateau: whale dealer cosmopolitan treasure island? Fashion show mall stand betting limits aria fremont street pot vegas givecamp? </p>\r\n<p>Haze caesar\'s palace the district odds high roller! Parlay feeling lucky hit high roller? Margaritaville cosmopolitan pot? Chateau straight wildcard fremont street the district margaritaville: spaghetti bowl lax hand bankroll. </p>\r\n<p>Aria insurance tapped out nightclubs the strip. Push the chandelier stratosphere betting limits whale house edge? Unlv lounges nightclubs hand payoff? Shooter fremont street margaritaville town square full house; zappos the palms stand house edge. </p>', 'clubs night party dance music dj alcohol celebs', 'Published', 16),
(48, 53, 'The best proposition bets', 'strategist', '2015-09-16 03:01:38', 'image1.png', '<p>Dice breaking even high roller. Payoff score dealer baccarat! Insurance the strip odds the mirage shuffle the chandelier rack pass. New york, new york capriotti\'s double down dealer pot two pair pass spaghetti bowl! </p>\r\n<p>Blind card counting shops at crystals high roller draw margaritaville aria. Pass capriotti\'s stand. Straight margaritaville the mirage tease glitter gluch the venetian? The district sin city full house lounges the chapel of love flamingo hotel probability loose. </p>\r\n<p>Stratosphere shooter insurance bankroll aria dealer glitter gluch. Straight dice bankroll new york, new york treasure island; the district parlay comps price! Push the joint new york, new york two pair lock insurance pit the palms! Price hand lounges comps the joint bust? </p>\r\n<p>Flamingo hotel hand hard rock hotel bankroll naked city, spaghetti bowl the mirage pot exposure. Body english the strip hand dayclubs tao. Glitter gluch bars pit boss draw straight: shooter baccarat rack fruit loop? Chateau capriotti\'s parlay hard rock hotel cosmopolitan feeling lucky: stratosphere lock the joint royal flush! </p>', 'dice craps bets props strategies hardways yo eleven snake eyes boxcars', 'Published', 12),
(52, 52, 'How to hold dice as you toss', 'dicemaster', '2015-09-16 03:03:09', 'image4.png', '<p>Chateau comps unlv loose vegas givecamp hard rock hotel fold? Shooter veer towers lounges comps blackjack shops at crystals flush; insurance double down payoff all in miracle mile shops mandalay bay! Ante lock vegas givecamp mandalay bay dayclubs city center! Rack ante sin city fashion show mall blackjack the strip town square spaghetti bowl. Full house the chapel of love flamingo hotel zappos vegas givecamp lax. City center golden nugget shops at crystals fruit loop dealer new york, new york loose. </p>\r\n<p>Insurance high roller blackjack hand stratosphere the chapel of love the venetian, glitter gluch two pair score full house straight stand. Shops at crystals flush payoff all in loose edge, exposure royal flush straight fremont street check! Cosmopolitan city center double down miracle mile shops the luxor shops at crystals, the chapel of love sin city veer towers chateau baccarat. Betting limits blind baccarat high roller the mirage house edge golden nugget aria? Probability cosmopolitan bluff top of the world fruit loop, swim-up blackjack treasure island sin city all in. Bars double down royal flush tapped out fruit loop lounges, baccarat fold dayclubs naked city. </p>\r\n<p>New york, new york fremont street sin city shooter chateau vegas givecamp baccarat, the venetian edge stand royal flush bust? Hard rock hotel insurance payoff nightclubs shuffle dayclubs the joint, the venetian push lounges veer towers top of the world. Straight score the pairs unlv flush body english push: mandalay bay pot hit all in the palms miracle mile shops? Pass miracle mile shops the mirage convention center blackjack the pairs; two pair bust house edge insurance high roller. Check caesar\'s palace pit nightclubs sin city edge hard rock hotel; aria loose parlay capriotti\'s card counting. Treasure island bankroll ante feeling lucky swim-up blackjack parlay the chandelier: cosmopolitan shooter dealer nightclubs aria fruit loop? </p>', 'craps dice vegas roll hold bounce table', 'Published', 18),
(53, 58, 'How does the Kelly Criterion apply to shooting craps?', 'highroller', '2015-09-16 03:03:09', 'image3.png', '<p>Tease sixth street miracle mile shops breaking even swim-up blackjack the joint insurance, feeling lucky new york, new york lounges the district loose margaritaville. Bust blind flamingo hotel sixth street flush fifth street check pit: swim-up blackjack price fremont street the district body english two pair. Payoff feeling lucky check top of the world caesar\'s palace pass: veer towers cosmopolitan full house baccarat? City center baccarat hand all in veer towers; bust caesar\'s palace dealer lock. All in aria bars feeling lucky chateau shops at crystals; haze royal flush draw the pairs. The chandelier parlay baccarat the district bars the mirage: straight tapped out betting limits tao lock; sin city nightclubs naked city breaking even. Fruit loop the strip cosmopolitan fremont street royal flush parlay; blind push straight insurance vegas givecamp; golden nugget feeling lucky bars dayclubs pass! Straight chips lock chateau push caesar\'s palace edge: bust house edge vdara loose shuffle! </p>\r\n<p>The mgm grand top of the world pot blind two pair hand: vdara nightclubs tapped out draw shops at crystals, card counting betting limits dice probability? Price bellagio two pair loose top of the world: swim-up blackjack wildcard shooter payoff. Cosmopolitan insurance the excalibur comps the mgm grand straight; sin city probability dice capriotti\'s aria? Glitter gluch edge lock cosmopolitan card counting margaritaville loose: city center haze fifth street miracle mile shops odds zappos! Glitter gluch ante wildcard flush house edge mandalay bay: new york, new york fashion show mall chips the pairs draw. Pass fifth street new york, new york pot double down body english cosmopolitan: all in rack price town square odds! Two pair pit boss the palms loose lounges shuffle bust: flush chateau sixth street cosmopolitan comps! The excalibur body english shops at crystals insurance whale lounges, parlay probability city center bluff high roller; pit draw treasure island ante! </p>', 'bets strategies money management kelly criterion', 'Published', 25),
(54, 51, 'Glad I found vegasipsum.com!', 'casinoowner', '2015-09-16 03:03:09', 'image7.png', '<p>Odds whale rack edge body english exposure shooter, hard rock hotel fremont street new york, new york loose unlv city center? Golden nugget the palms vdara lock double down tao; top of the world the luxor ante aria? Draw hard rock hotel pot lounges fremont street: shops at crystals chips vegas givecamp shooter! Straight rack miracle mile shops edge draw: tao house edge the excalibur lax? Haze convention center the chapel of love pit chateau flush: edge royal flush shuffle the mgm grand bars? Check miracle mile shops payoff glitter gluch cosmopolitan: margaritaville chips the pairs body english. </p>', 'lorem ipsum vegas filler text', 'Published', 23),
(55, 53, 'The best proposition bets', 'strategist', '2015-09-16 03:03:09', 'image1.png', '<p>Dice breaking even high roller. Payoff score dealer baccarat! Insurance the strip odds the mirage shuffle the chandelier rack pass. New york, new york capriotti\'s double down dealer pot two pair pass spaghetti bowl! </p>\r\n<p>Blind card counting shops at crystals high roller draw margaritaville aria. Pass capriotti\'s stand. Straight margaritaville the mirage tease glitter gluch the venetian? The district sin city full house lounges the chapel of love flamingo hotel probability loose. </p>\r\n<p>Stratosphere shooter insurance bankroll aria dealer glitter gluch. Straight dice bankroll new york, new york treasure island; the district parlay comps price! Push the joint new york, new york two pair lock insurance pit the palms! Price hand lounges comps the joint bust? </p>\r\n<p>Flamingo hotel hand hard rock hotel bankroll naked city, spaghetti bowl the mirage pot exposure. Body english the strip hand dayclubs tao. Glitter gluch bars pit boss draw straight: shooter baccarat rack fruit loop? Chateau capriotti\'s parlay hard rock hotel cosmopolitan feeling lucky: stratosphere lock the joint royal flush! </p>', 'dice craps bets props strategies hardways yo eleven snake eyes boxcars', 'Published', 22),
(56, 59, 'Gluttony Greed Lust Sloth Wrath Envy Pride', 'pahrump', '2015-09-16 03:03:09', 'image8.png', '<p>Two pair town square pass pit boss the luxor chips? All in card counting dice? Tao high roller probability golden nugget exposure lounges house edge the pairs. Glitter gluch swim-up blackjack lock shuffle chateau hit unlv the chandelier. </p>\r\n<p>Push draw all in spaghetti bowl blind: the mgm grand hard rock hotel naked city comps? Double down score ante unlv! Shuffle card counting pass flamingo hotel sin city treasure island! Lax blackjack high roller the chapel of love fashion show mall unlv: miracle mile shops naked city bust full house. </p>\r\n<p>Chateau the strip stand double down vdara vegas givecamp dealer? Whale new york, new york stand ante sixth street pit, shuffle aria convention center price? The excalibur double down spaghetti bowl? Pit city center the joint fifth street baccarat vdara card counting miracle mile shops. </p>', 'deadly sins hell evil devil damnation', 'Published', 15),
(62, 51, 'Glad I found vegasipsum.com!', 'casinoowner', '2015-09-16 03:04:28', 'image7.png', '<p>Odds whale rack edge body english exposure shooter, hard rock hotel fremont street new york, new york loose unlv city center? Golden nugget the palms vdara lock double down tao; top of the world the luxor ante aria? Draw hard rock hotel pot lounges fremont street: shops at crystals chips vegas givecamp shooter! Straight rack miracle mile shops edge draw: tao house edge the excalibur lax? Haze convention center the chapel of love pit chateau flush: edge royal flush shuffle the mgm grand bars? Check miracle mile shops payoff glitter gluch cosmopolitan: margaritaville chips the pairs body english. </p>', 'lorem ipsum vegas filler text', 'Published', 26),
(64, 53, 'The best proposition bets', 'strategist', '2015-09-16 03:04:28', 'image1.png', '<p>Dice breaking even high roller. Payoff score dealer baccarat! Insurance the strip odds the mirage shuffle the chandelier rack pass. New york, new york capriotti\'s double down dealer pot two pair pass spaghetti bowl! </p>\r\n<p>Blind card counting shops at crystals high roller draw margaritaville aria. Pass capriotti\'s stand. Straight margaritaville the mirage tease glitter gluch the venetian? The district sin city full house lounges the chapel of love flamingo hotel probability loose. </p>\r\n<p>Stratosphere shooter insurance bankroll aria dealer glitter gluch. Straight dice bankroll new york, new york treasure island; the district parlay comps price! Push the joint new york, new york two pair lock insurance pit the palms! Price hand lounges comps the joint bust? </p>\r\n<p>Flamingo hotel hand hard rock hotel bankroll naked city, spaghetti bowl the mirage pot exposure. Body english the strip hand dayclubs tao. Glitter gluch bars pit boss draw straight: shooter baccarat rack fruit loop? Chateau capriotti\'s parlay hard rock hotel cosmopolitan feeling lucky: stratosphere lock the joint royal flush! </p>', 'dice craps bets props strategies hardways yo eleven snake eyes boxcars', 'Published', 23),
(65, 69, 'Seafood, Seafood, Seafood', 'robin', '2015-09-17 02:44:30', 'image13.png', 'Danio yellow bass beachsalmon giant sea bass. Cutthroat eel Sacramento splittail long-finned char spadefish sweeper. Cod southern flounder ziege lake whitefish Long-finned sand diver. Mosshead warbonnet false moray brook lamprey southern flounder northern Stargazer yellow weaver. Sacramento splittail requiem shark goby lenok Black prickleback red snapper Bombay duck mouthbrooder electric stargazer sailfin silverside. Lemon sole mako shark river loach; morwong spiderfish tidewater goby dartfish false moray Sacramento blackfish?\r\n\r\nBitterling longfin escolar Moses sole, bigscale fish tonguefish; sergeant major pickerel codling threadfin bream jackfish. Saw shark tapetail boafish horsefish; cuskfish orange roughy mail-cheeked fish, \"Steve fish,\" roanoke bass Alaska blackfish. Brown trout, hardhead catfish lined sole, pollock basking shark yellow bass lancetfish white marlin. Collared dogfish sand stargazer. Redmouth whalefish elephantnose fish coley climbing perch: gombessa, black bass velvet-belly shark whale catfish. Electric knifefish southern Dolly Varden grass carp zingel roanoke bass longjaw mudsucker hoki tigerperch.', 'seafood tuna restaurant cuisine food', 'Published', 30),
(66, 69, 'Best Sushi Restaurant', 'robin', '2015-09-17 03:34:03', 'image11.png', '<p>Bar robusta mocha et foam aromatic aroma. Siphon sweet, blue mountain in wings viennese, single origin breve shop trifecta bar decaffeinated. That cup variety pumpkin spice americano macchiato body breve. Flavour cream robust dark, milk extraction barista caffeine medium.</p>\r\n<p>Body, frappuccino redeye, acerbic sweet pumpkin spice whipped rich caramelization. As affogato roast skinny grinder decaffeinated so plunger pot sugar and robust robusta. Iced blue mountain, mocha frappuccino, redeye irish decaffeinated affogato filter. Qui eu filter lungo dark steamed wings aged acerbic.</p>', 'sushi restaurant japanese food cuisine', 'Published', 45),
(67, 69, 'Favorite Buffet', 'robin', '2015-09-17 03:35:22', 'image10.png', 'Cupcake ipsum dolor. Sit amet caramels pastry carrot cake fruitcake jelly croissant lollipop. Halvah pudding donut icing croissant topping.\r\nTopping gingerbread fruitcake dessert croissant icing bear claw cheesecake tart. Sweet sesame snaps cheesecake. Cookie donut halvah sweet bonbon cake fruitcake. Donut chupa chups cake.\r\nChocolate gummi bears jelly halvah muffin. Lollipop dessert topping icing. Liquorice halvah sugar plum cupcake powder candy canes tootsie roll oat cake biscuit.', 'buffet food cuisine casino', 'Published', 60),
(68, 69, 'Crawfish Etoufee and Gumbo', 'robin', '2015-09-17 03:37:21', 'image14.png', 'Boucherie file beignet canaille beignet gumbo. Hot sauce levee boiled crawfish tasso farmer\'s market gulf shrimp yams Mardi Gras canaille etoufee. Bbq sac a lait pecan pie fais do do cher interstate King Cake boudin boiled crawfish. Farmer\'s market couillon Boudreaux sauce piquante coffee. Fauxcheaux gulf shrimp smoked sausage fais do do merci beaucoup envie merci beaucoup levee mirliton levee. Po-boy football andouille catahoula King Cake bayou bourre sac a lait Thibideaux catahoula. Pirogue etoufee bisque macque choux football gulf shrimp Acadiana. \r\n\r\nLagniappe turducken jambalaya crawfish cayenne sauce piquante barbed wire sauce piquante King Cake crawfish. Bonjour iced tea andouille gumbo catahoula football mirliton interstate. Pecan pie alligator jambalaya levee hunting Fauxcheaux fried catfish couillon canaille po-boy. Fried catfish andouille food sauce piquante andouille po-boy macque choux. Acadiana mirliton envie boucherie boucherie macque choux Lafayette. Sa fait chaud jambalaya gumbo bread pudding fried chicken. Hot sauce beignet fais do do food andouille bayou bread pudding iced tea fais do do macque choux. \r\n', 'louisiana new orleans cajun restaurant food', 'Published', 33),
(69, 69, 'Cupcakes Galore', 'robin', '2015-09-17 03:38:54', 'image14.png', '<p>Cupcake ipsum dolor sit amet sesame snaps gingerbread dragee. Donut brownie jelly-o sesame snaps wafer cheesecake pastry croissant. Ice cream chocolate bar dragée halvah brownie marshmallow carrot cake oat cake.</p><p>Fruitcake candy candy canes chocolate bar. Chupa chups dessert halvah souffle halvah liquorice donut oat cake. Bonbon lollipop biscuit cookie tiramisu chocolate bar jelly caramels cake.</p><p>Cake candy canes carrot cake jujubes pudding marzipan. Jelly-o topping lollipop lemon drops tiramisu donut sweet sugar plum. Caramels dragee brownie.</p><p>Wafer fruitcake sweet roll pie. Marzipan sesame snaps jelly-o. Marshmallow sweet chocolate bar sugar plum souffle.</p>', 'cupcakes dessert pastries', 'Published', 30),
(70, 69, 'Vegas Downtown Eats', 'robin', '2015-09-17 03:40:01', 'image15.png', '<p>Pot body english golden nugget sin city stand; feeling lucky the pairs city center house edge? Unlv blackjack sixth street capriotti\'s! Feeling lucky push the mgm grand? Draw tapped out royal flush the mirage the pairs feeling lucky; lock sixth street flamingo hotel fashion show mall! </p>\r\n<p>Draw vegas givecamp bars ante! Parlay house edge straight push? Shops at crystals probability draw body english mandalay bay; the pairs fold margaritaville blackjack. Glitter gluch the venetian parlay zappos straight rack! </p>\r\n<p>Body english fremont street loose bellagio bars! Swim-up blackjack the chandelier city center pit boss! Full house sin city house edge pit edge mandalay bay; vegas givecamp unlv bluff stand? Top of the world sixth street convention center fremont street blind mandalay bay? </p>\r\n<p>Two pair insurance pit the mgm grand card counting golden nugget? Blind margaritaville insurance the joint push hit score! Fifth street bust feeling lucky mandalay bay hand straight shops at crystals? Flamingo hotel lounges nightclubs top of the world cosmopolitan score miracle mile shops. </p>', 'vegas downtown restaurants food', 'Published', 36),
(71, 69, 'Find Dining in Vegas', 'robin', '2015-09-17 03:47:58', 'image12.png', 'Bacon ipsum dolor amet sirloin sausage bacon tenderloin jowl beef hamburger kielbasa swine shankle tongue drumstick. Ribeye venison landjaeger shank. Cupim short ribs ribeye kevin, tri-tip bresaola jerky prosciutto andouille short loin. Meatloaf tail swine pancetta, venison beef ribs jowl ground round rump ham hock leberkas cow pork belly doner chuck.\r\n\r\nChicken meatball flank, jerky beef ribs ribeye rump cupim andouille shankle jowl picanha brisket pig. Boudin chicken pork chop, porchetta filet mignon ball tip tri-tip jowl pancetta ham hock swine. Shoulder doner ham hock filet mignon brisket jerky capicola. Beef swine shoulder turkey brisket, ground round chicken frankfurter pig ham hock bacon leberkas sirloin pork chop. Pork belly swine drumstick, turkey strip steak ham bacon fatback tongue.\r\n\r\nDrumstick prosciutto sausage kielbasa pork loin short ribs, doner bresaola hamburger shankle turkey. Ball tip spare ribs pancetta pork belly tongue chuck hamburger prosciutto kielbasa jerky cow ham tri-tip pastrami shoulder. Biltong sausage picanha kielbasa beef venison drumstick strip steak ham hock. Flank ham landjaeger kielbasa turkey andouille pancetta.', 'fine dining restaurants chef food', 'Published', 61),
(72, 72, 'Qu\'est que c\'est?', 'eleanor', '2015-09-18 02:53:36', 'image16.png', 'Verum ad istam omnem orationem brevis est defensio. Nam quoad aetas M. Caeli dare potuit isti suspicioni locum, fuit primum ipsius pudore, deinde etiam patris diligentia disciplinaque munita. Qui ut huic virilem togam deditÅ¡nihil dicam hoc loco de me; tantum sit, quantum vos existimatis; hoc dicam, hunc a patre continuo ad me esse deductum; nemo hunc M. Caelium in illo aetatis flore vidit nisi aut cum patre aut mecum aut in M. Crassi castissima domo, cum artibus honestissimis erudiretur.', 'paris eiffel tower vegas hotel french', 'Published', 36),
(74, 52, 'How to hold dice as you toss', 'dicemaster', '2015-09-19 04:16:16', 'image4.png', '<p>Chateau comps unlv loose vegas givecamp hard rock hotel fold? Shooter veer towers lounges comps blackjack shops at crystals flush; insurance double down payoff all in miracle mile shops mandalay bay! Ante lock vegas givecamp mandalay bay dayclubs city center! Rack ante sin city fashion show mall blackjack the strip town square spaghetti bowl. Full house the chapel of love flamingo hotel zappos vegas givecamp lax. City center golden nugget shops at crystals fruit loop dealer new york, new york loose. </p>\r\n<p>Insurance high roller blackjack hand stratosphere the chapel of love the venetian, glitter gluch two pair score full house straight stand. Shops at crystals flush payoff all in loose edge, exposure royal flush straight fremont street check! Cosmopolitan city center double down miracle mile shops the luxor shops at crystals, the chapel of love sin city veer towers chateau baccarat. Betting limits blind baccarat high roller the mirage house edge golden nugget aria? Probability cosmopolitan bluff top of the world fruit loop, swim-up blackjack treasure island sin city all in. Bars double down royal flush tapped out fruit loop lounges, baccarat fold dayclubs naked city. </p>\r\n<p>New york, new york fremont street sin city shooter chateau vegas givecamp baccarat, the venetian edge stand royal flush bust? Hard rock hotel insurance payoff nightclubs shuffle dayclubs the joint, the venetian push lounges veer towers top of the world. Straight score the pairs unlv flush body english push: mandalay bay pot hit all in the palms miracle mile shops? Pass miracle mile shops the mirage convention center blackjack the pairs; two pair bust house edge insurance high roller. Check caesar\'s palace pit nightclubs sin city edge hard rock hotel; aria loose parlay capriotti\'s card counting. Treasure island bankroll ante feeling lucky swim-up blackjack parlay the chandelier: cosmopolitan shooter dealer nightclubs aria fruit loop? </p>', 'craps dice vegas roll hold bounce table', 'Published', 32),
(75, 53, 'How does off-and-on work on come-bets?', 'doctordice', '2015-09-19 04:16:16', 'image5.png', '<p>Haze naked city spaghetti bowl the excalibur comps: the chapel of love exposure flush probability. The joint blackjack aria push the pairs sixth street the venetian zappos. Straight lounges top of the world insurance the strip! Card counting convention center chips the chapel of love bankroll, price pit the district parlay? </p>\r\n<p>The venetian margaritaville fremont street fashion show mall hit fifth street the strip swim-up blackjack? Flamingo hotel card counting nightclubs spaghetti bowl fifth street caesar\'s palace rack hand! Two pair flamingo hotel hit? Vegas givecamp lock nightclubs bluff golden nugget the joint, double down tease top of the world the excalibur. </p>\r\n<p>Pot hard rock hotel the chapel of love! Bust loose town square rack the luxor wildcard shops at crystals the palms. The chandelier dealer parlay margaritaville royal flush pass top of the world. Flamingo hotel blackjack nightclubs top of the world treasure island shops at crystals? </p>', 'craps strategies bets dealers come odds', 'Published', 27),
(76, 58, 'How does the Kelly Criterion apply to shooting craps?', 'highroller', '2015-09-19 04:16:16', 'image3.png', '<p>Tease sixth street miracle mile shops breaking even swim-up blackjack the joint insurance, feeling lucky new york, new york lounges the district loose margaritaville. Bust blind flamingo hotel sixth street flush fifth street check pit: swim-up blackjack price fremont street the district body english two pair. Payoff feeling lucky check top of the world caesar\'s palace pass: veer towers cosmopolitan full house baccarat? City center baccarat hand all in veer towers; bust caesar\'s palace dealer lock. All in aria bars feeling lucky chateau shops at crystals; haze royal flush draw the pairs. The chandelier parlay baccarat the district bars the mirage: straight tapped out betting limits tao lock; sin city nightclubs naked city breaking even. Fruit loop the strip cosmopolitan fremont street royal flush parlay; blind push straight insurance vegas givecamp; golden nugget feeling lucky bars dayclubs pass! Straight chips lock chateau push caesar\'s palace edge: bust house edge vdara loose shuffle! </p>\r\n<p>The mgm grand top of the world pot blind two pair hand: vdara nightclubs tapped out draw shops at crystals, card counting betting limits dice probability? Price bellagio two pair loose top of the world: swim-up blackjack wildcard shooter payoff. Cosmopolitan insurance the excalibur comps the mgm grand straight; sin city probability dice capriotti\'s aria? Glitter gluch edge lock cosmopolitan card counting margaritaville loose: city center haze fifth street miracle mile shops odds zappos! Glitter gluch ante wildcard flush house edge mandalay bay: new york, new york fashion show mall chips the pairs draw. Pass fifth street new york, new york pot double down body english cosmopolitan: all in rack price town square odds! Two pair pit boss the palms loose lounges shuffle bust: flush chateau sixth street cosmopolitan comps! The excalibur body english shops at crystals insurance whale lounges, parlay probability city center bluff high roller; pit draw treasure island ante! </p>', 'bets strategies money management kelly criterion', 'Published', 32),
(77, 59, 'Comps: The secret behind those freebies', 'highroller', '2015-09-19 04:16:16', 'image6.png', '<p>Sin city pass shops at crystals hard rock hotel push shuffle: hand loose veer towers chateau! Full house tease draw nightclubs. Golden nugget haze capriotti\'s draw? Mandalay bay the palms vdara straight bellagio: the venetian baccarat edge convention center. </p>\r\n<p>Shops at crystals tease unlv hard rock hotel shooter parlay: bars comps city center flush? Probability hard rock hotel ante fashion show mall haze? Comps high roller the excalibur chateau bars blackjack, breaking even hand odds dealer! Fold the joint payoff chateau? </p>\r\n<p>Baccarat bellagio the district chips price shooter the strip. Probability the palms straight the excalibur. Fold shooter stratosphere draw miracle mile shops. Parlay full house glitter gluch royal flush chateau dealer? </p>\r\n<p>Stratosphere straight pit boss swim-up blackjack golden nugget flamingo hotel? Cosmopolitan the palms odds stand shuffle; town square sin city bellagio comps? Hit haze shooter. Vdara price treasure island haze aria the district hit the palms! </p>\r\n<p>Town square fremont street feeling lucky city center stand! Rack shooter pit boss two pair lock town square? Tease blind lock comps the palms wildcard haze new york, new york! Body english vdara town square convention center edge chateau, the excalibur draw aria chips? </p>', 'comps deals casinos free club cards food shows', 'Published', 26),
(78, 51, 'Glad I found vegasipsum.com!', 'casinoowner', '2015-09-19 04:16:16', 'image7.png', '<p>Odds whale rack edge body english exposure shooter, hard rock hotel fremont street new york, new york loose unlv city center? Golden nugget the palms vdara lock double down tao; top of the world the luxor ante aria? Draw hard rock hotel pot lounges fremont street: shops at crystals chips vegas givecamp shooter! Straight rack miracle mile shops edge draw: tao house edge the excalibur lax? Haze convention center the chapel of love pit chateau flush: edge royal flush shuffle the mgm grand bars? Check miracle mile shops payoff glitter gluch cosmopolitan: margaritaville chips the pairs body english. </p>', 'lorem ipsum vegas filler text', 'Published', 28),
(79, 58, 'Nightclub Scene', 'partygirl', '2015-09-19 04:16:16', 'image2.png', '<p>Convention center sixth street body english cosmopolitan the excalibur new york, new york. Straight the luxor chateau. Veer towers vdara aria shops at crystals city center mandalay bay tao body english! Straight dayclubs pit boss tao. </p>\r\n<p>Haze glitter gluch two pair bluff check double down, loose vegas givecamp bars vdara? Full house pit boss score! Push pass naked city vdara! The chapel of love sixth street town square dice unlv? </p>\r\n<p>Chips royal flush shooter zappos straight. Fold new york, new york shooter price zappos blackjack the district cosmopolitan? Flamingo hotel shuffle golden nugget aria haze glitter gluch: two pair bellagio the chapel of love fifth street! The mirage the luxor bars score margaritaville dayclubs. </p>\r\n<p>Dealer price vdara hand check bars comps? Odds vegas givecamp city center double down fruit loop? Rack fold pass bluff haze chateau: whale dealer cosmopolitan treasure island? Fashion show mall stand betting limits aria fremont street pot vegas givecamp? </p>\r\n<p>Haze caesar\'s palace the district odds high roller! Parlay feeling lucky hit high roller? Margaritaville cosmopolitan pot? Chateau straight wildcard fremont street the district margaritaville: spaghetti bowl lax hand bankroll. </p>\r\n<p>Aria insurance tapped out nightclubs the strip. Push the chandelier stratosphere betting limits whale house edge? Unlv lounges nightclubs hand payoff? Shooter fremont street margaritaville town square full house; zappos the palms stand house edge. </p>', 'clubs night party dance music dj alcohol celebs', 'Published', 31),
(80, 53, 'The best proposition bets', 'strategist', '2015-09-19 04:16:16', 'image1.png', '<p>Dice breaking even high roller. Payoff score dealer baccarat! Insurance the strip odds the mirage shuffle the chandelier rack pass. New york, new york capriotti\'s double down dealer pot two pair pass spaghetti bowl! </p>\r\n<p>Blind card counting shops at crystals high roller draw margaritaville aria. Pass capriotti\'s stand. Straight margaritaville the mirage tease glitter gluch the venetian? The district sin city full house lounges the chapel of love flamingo hotel probability loose. </p>\r\n<p>Stratosphere shooter insurance bankroll aria dealer glitter gluch. Straight dice bankroll new york, new york treasure island; the district parlay comps price! Push the joint new york, new york two pair lock insurance pit the palms! Price hand lounges comps the joint bust? </p>\r\n<p>Flamingo hotel hand hard rock hotel bankroll naked city, spaghetti bowl the mirage pot exposure. Body english the strip hand dayclubs tao. Glitter gluch bars pit boss draw straight: shooter baccarat rack fruit loop? Chateau capriotti\'s parlay hard rock hotel cosmopolitan feeling lucky: stratosphere lock the joint royal flush! </p>', 'dice craps bets props strategies hardways yo eleven snake eyes boxcars', 'Published', 29);
INSERT INTO `cms_posts` (`post_id`, `post_cat_id`, `post_title`, `post_author`, `post_date`, `post_image`, `post_content`, `post_tags`, `post_status`, `post_views_count`) VALUES
(81, 51, 'Gluttony Greed Lust Sloth Wrath Envy Pride', 'pahrump', '2015-09-19 04:16:16', 'image8.png', '<p>Two pair town square pass pit boss the luxor chips? All in card counting dice? Tao high roller probability golden nugget exposure lounges house edge the pairs. Glitter gluch swim-up blackjack lock shuffle chateau hit unlv the chandelier. </p>\r\n<p>Push draw all in spaghetti bowl blind: the mgm grand hard rock hotel naked city comps? Double down score ante unlv! Shuffle card counting pass flamingo hotel sin city treasure island! Lax blackjack high roller the chapel of love fashion show mall unlv: miracle mile shops naked city bust full house. </p>\r\n<p>Chateau the strip stand double down vdara vegas givecamp dealer? Whale new york, new york stand ante sixth street pit, shuffle aria convention center price? The excalibur double down spaghetti bowl? Pit city center the joint fifth street baccarat vdara card counting miracle mile shops. </p>', 'deadly sins hell evil devil damnation', 'Published', 33),
(91, 66, 'Comps: The secret behind those freebies', 'highroller', '2015-09-19 04:34:44', 'image6.png', '<p>Sin city pass shops at crystals hard rock hotel push shuffle: hand loose veer towers chateau! Full house tease draw nightclubs. Golden nugget haze capriotti\'s draw? Mandalay bay the palms vdara straight bellagio: the venetian baccarat edge convention center. </p>\r\n<p>Shops at crystals tease unlv hard rock hotel shooter parlay: bars comps city center flush? Probability hard rock hotel ante fashion show mall haze? Comps high roller the excalibur chateau bars blackjack, breaking even hand odds dealer! Fold the joint payoff chateau? </p>\r\n<p>Baccarat bellagio the district chips price shooter the strip. Probability the palms straight the excalibur. Fold shooter stratosphere draw miracle mile shops. Parlay full house glitter gluch royal flush chateau dealer? </p>\r\n<p>Stratosphere straight pit boss swim-up blackjack golden nugget flamingo hotel? Cosmopolitan the palms odds stand shuffle; town square sin city bellagio comps? Hit haze shooter. Vdara price treasure island haze aria the district hit the palms! </p>\r\n<p>Town square fremont street feeling lucky city center stand! Rack shooter pit boss two pair lock town square? Tease blind lock comps the palms wildcard haze new york, new york! Body english vdara town square convention center edge chateau, the excalibur draw aria chips? </p>', 'comps deals casinos free club cards food shows', 'Published', 34),
(92, 58, 'How does the Kelly Criterion apply to shooting craps?', 'highroller', '2015-09-19 04:34:44', 'image3.png', '<p>Tease sixth street miracle mile shops breaking even swim-up blackjack the joint insurance, feeling lucky new york, new york lounges the district loose margaritaville. Bust blind flamingo hotel sixth street flush fifth street check pit: swim-up blackjack price fremont street the district body english two pair. Payoff feeling lucky check top of the world caesar\'s palace pass: veer towers cosmopolitan full house baccarat? City center baccarat hand all in veer towers; bust caesar\'s palace dealer lock. All in aria bars feeling lucky chateau shops at crystals; haze royal flush draw the pairs. The chandelier parlay baccarat the district bars the mirage: straight tapped out betting limits tao lock; sin city nightclubs naked city breaking even. Fruit loop the strip cosmopolitan fremont street royal flush parlay; blind push straight insurance vegas givecamp; golden nugget feeling lucky bars dayclubs pass! Straight chips lock chateau push caesar\'s palace edge: bust house edge vdara loose shuffle! </p>\r\n<p>The mgm grand top of the world pot blind two pair hand: vdara nightclubs tapped out draw shops at crystals, card counting betting limits dice probability? Price bellagio two pair loose top of the world: swim-up blackjack wildcard shooter payoff. Cosmopolitan insurance the excalibur comps the mgm grand straight; sin city probability dice capriotti\'s aria? Glitter gluch edge lock cosmopolitan card counting margaritaville loose: city center haze fifth street miracle mile shops odds zappos! Glitter gluch ante wildcard flush house edge mandalay bay: new york, new york fashion show mall chips the pairs draw. Pass fifth street new york, new york pot double down body english cosmopolitan: all in rack price town square odds! Two pair pit boss the palms loose lounges shuffle bust: flush chateau sixth street cosmopolitan comps! The excalibur body english shops at crystals insurance whale lounges, parlay probability city center bluff high roller; pit draw treasure island ante! </p>', 'bets strategies money management kelly criterion', 'Published', 34),
(97, 59, 'Comps: The secret behind those freebies', 'highroller', '2015-09-19 04:35:23', 'image6.png', '<p>Sin city pass shops at crystals hard rock hotel push shuffle: hand loose veer towers chateau! Full house tease draw nightclubs. Golden nugget haze capriotti\'s draw? Mandalay bay the palms vdara straight bellagio: the venetian baccarat edge convention center. </p>\r\n<p>Shops at crystals tease unlv hard rock hotel shooter parlay: bars comps city center flush? Probability hard rock hotel ante fashion show mall haze? Comps high roller the excalibur chateau bars blackjack, breaking even hand odds dealer! Fold the joint payoff chateau? </p>\r\n<p>Baccarat bellagio the district chips price shooter the strip. Probability the palms straight the excalibur. Fold shooter stratosphere draw miracle mile shops. Parlay full house glitter gluch royal flush chateau dealer? </p>\r\n<p>Stratosphere straight pit boss swim-up blackjack golden nugget flamingo hotel? Cosmopolitan the palms odds stand shuffle; town square sin city bellagio comps? Hit haze shooter. Vdara price treasure island haze aria the district hit the palms! </p>\r\n<p>Town square fremont street feeling lucky city center stand! Rack shooter pit boss two pair lock town square? Tease blind lock comps the palms wildcard haze new york, new york! Body english vdara town square convention center edge chateau, the excalibur draw aria chips? </p>', 'comps deals casinos free club cards food shows', 'Published', 34),
(98, 59, 'Comps: The secret behind those freebies', 'highroller', '2015-09-19 04:35:23', 'image6.png', '<p>Sin city pass shops at crystals hard rock hotel push shuffle: hand loose veer towers chateau! Full house tease draw nightclubs. Golden nugget haze capriotti\'s draw? Mandalay bay the palms vdara straight bellagio: the venetian baccarat edge convention center. </p>\r\n<p>Shops at crystals tease unlv hard rock hotel shooter parlay: bars comps city center flush? Probability hard rock hotel ante fashion show mall haze? Comps high roller the excalibur chateau bars blackjack, breaking even hand odds dealer! Fold the joint payoff chateau? </p>\r\n<p>Baccarat bellagio the district chips price shooter the strip. Probability the palms straight the excalibur. Fold shooter stratosphere draw miracle mile shops. Parlay full house glitter gluch royal flush chateau dealer? </p>\r\n<p>Stratosphere straight pit boss swim-up blackjack golden nugget flamingo hotel? Cosmopolitan the palms odds stand shuffle; town square sin city bellagio comps? Hit haze shooter. Vdara price treasure island haze aria the district hit the palms! </p>\r\n<p>Town square fremont street feeling lucky city center stand! Rack shooter pit boss two pair lock town square? Tease blind lock comps the palms wildcard haze new york, new york! Body english vdara town square convention center edge chateau, the excalibur draw aria chips? </p>', 'comps deals casinos free club cards food shows', 'Published', 36),
(99, 53, 'How does off-and-on work on come-bets?', 'doctordice', '2015-09-19 05:26:33', 'image5.png', '<p>Haze naked city spaghetti bowl the excalibur comps: the chapel of love exposure flush probability. The joint blackjack aria push the pairs sixth street the venetian zappos. Straight lounges top of the world insurance the strip! Card counting convention center chips the chapel of love bankroll, price pit the district parlay? </p>\r\n<p>The venetian margaritaville fremont street fashion show mall hit fifth street the strip swim-up blackjack? Flamingo hotel card counting nightclubs spaghetti bowl fifth street caesar\'s palace rack hand! Two pair flamingo hotel hit? Vegas givecamp lock nightclubs bluff golden nugget the joint, double down tease top of the world the excalibur. </p>\r\n<p>Pot hard rock hotel the chapel of love! Bust loose town square rack the luxor wildcard shops at crystals the palms. The chandelier dealer parlay margaritaville royal flush pass top of the world. Flamingo hotel blackjack nightclubs top of the world treasure island shops at crystals? </p>', 'craps strategies bets dealers come odds', 'Published', 56),
(100, 58, 'How does the Kelly Criterion apply to shooting craps?', 'highroller', '2015-09-19 05:26:33', 'image3.png', '<p>Tease sixth street miracle mile shops breaking even swim-up blackjack the joint insurance, feeling lucky new york, new york lounges the district loose margaritaville. Bust blind flamingo hotel sixth street flush fifth street check pit: swim-up blackjack price fremont street the district body english two pair. Payoff feeling lucky check top of the world caesar\'s palace pass: veer towers cosmopolitan full house baccarat? City center baccarat hand all in veer towers; bust caesar\'s palace dealer lock. All in aria bars feeling lucky chateau shops at crystals; haze royal flush draw the pairs. The chandelier parlay baccarat the district bars the mirage: straight tapped out betting limits tao lock; sin city nightclubs naked city breaking even. Fruit loop the strip cosmopolitan fremont street royal flush parlay; blind push straight insurance vegas givecamp; golden nugget feeling lucky bars dayclubs pass! Straight chips lock chateau push caesar\'s palace edge: bust house edge vdara loose shuffle! </p>\r\n<p>The mgm grand top of the world pot blind two pair hand: vdara nightclubs tapped out draw shops at crystals, card counting betting limits dice probability? Price bellagio two pair loose top of the world: swim-up blackjack wildcard shooter payoff. Cosmopolitan insurance the excalibur comps the mgm grand straight; sin city probability dice capriotti\'s aria? Glitter gluch edge lock cosmopolitan card counting margaritaville loose: city center haze fifth street miracle mile shops odds zappos! Glitter gluch ante wildcard flush house edge mandalay bay: new york, new york fashion show mall chips the pairs draw. Pass fifth street new york, new york pot double down body english cosmopolitan: all in rack price town square odds! Two pair pit boss the palms loose lounges shuffle bust: flush chateau sixth street cosmopolitan comps! The excalibur body english shops at crystals insurance whale lounges, parlay probability city center bluff high roller; pit draw treasure island ante! </p>', 'bets strategies money management kelly criterion', 'Published', 47),
(101, 59, 'Comps: The secret behind those freebies', 'highroller', '2015-09-19 05:26:33', 'image6.png', '<p>Sin city pass shops at crystals hard rock hotel push shuffle: hand loose veer towers chateau! Full house tease draw nightclubs. Golden nugget haze capriotti\'s draw? Mandalay bay the palms vdara straight bellagio: the venetian baccarat edge convention center. </p>\r\n<p>Shops at crystals tease unlv hard rock hotel shooter parlay: bars comps city center flush? Probability hard rock hotel ante fashion show mall haze? Comps high roller the excalibur chateau bars blackjack, breaking even hand odds dealer! Fold the joint payoff chateau? </p>\r\n<p>Baccarat bellagio the district chips price shooter the strip. Probability the palms straight the excalibur. Fold shooter stratosphere draw miracle mile shops. Parlay full house glitter gluch royal flush chateau dealer? </p>\r\n<p>Stratosphere straight pit boss swim-up blackjack golden nugget flamingo hotel? Cosmopolitan the palms odds stand shuffle; town square sin city bellagio comps? Hit haze shooter. Vdara price treasure island haze aria the district hit the palms! </p>\r\n<p>Town square fremont street feeling lucky city center stand! Rack shooter pit boss two pair lock town square? Tease blind lock comps the palms wildcard haze new york, new york! Body english vdara town square convention center edge chateau, the excalibur draw aria chips? </p>', 'comps deals casinos free club cards food shows', 'Published', 41),
(102, 51, 'Glad I found vegasipsum.com!', 'casinoowner', '2015-09-19 05:26:33', 'image7.png', '<p>Odds whale rack edge body english exposure shooter, hard rock hotel fremont street new york, new york loose unlv city center? Golden nugget the palms vdara lock double down tao; top of the world the luxor ante aria? Draw hard rock hotel pot lounges fremont street: shops at crystals chips vegas givecamp shooter! Straight rack miracle mile shops edge draw: tao house edge the excalibur lax? Haze convention center the chapel of love pit chateau flush: edge royal flush shuffle the mgm grand bars? Check miracle mile shops payoff glitter gluch cosmopolitan: margaritaville chips the pairs body english. </p>', 'lorem ipsum vegas filler text', 'Published', 40),
(103, 66, 'Nightclub Scene', 'partygirl', '2015-09-19 05:26:33', 'image2.png', '<p>Convention center sixth street body english cosmopolitan the excalibur new york, new york. Straight the luxor chateau. Veer towers vdara aria shops at crystals city center mandalay bay tao body english! Straight dayclubs pit boss tao. </p>\r\n<p>Haze glitter gluch two pair bluff check double down, loose vegas givecamp bars vdara? Full house pit boss score! Push pass naked city vdara! The chapel of love sixth street town square dice unlv? </p>\r\n<p>Chips royal flush shooter zappos straight. Fold new york, new york shooter price zappos blackjack the district cosmopolitan? Flamingo hotel shuffle golden nugget aria haze glitter gluch: two pair bellagio the chapel of love fifth street! The mirage the luxor bars score margaritaville dayclubs. </p>\r\n<p>Dealer price vdara hand check bars comps? Odds vegas givecamp city center double down fruit loop? Rack fold pass bluff haze chateau: whale dealer cosmopolitan treasure island? Fashion show mall stand betting limits aria fremont street pot vegas givecamp? </p>\r\n<p>Haze caesar\'s palace the district odds high roller! Parlay feeling lucky hit high roller? Margaritaville cosmopolitan pot? Chateau straight wildcard fremont street the district margaritaville: spaghetti bowl lax hand bankroll. </p>\r\n<p>Aria insurance tapped out nightclubs the strip. Push the chandelier stratosphere betting limits whale house edge? Unlv lounges nightclubs hand payoff? Shooter fremont street margaritaville town square full house; zappos the palms stand house edge. </p>', 'clubs night party dance music dj alcohol celebs', 'Published', 43),
(104, 73, 'The best proposition bets', 'strategist', '2015-09-19 05:26:33', 'image1.png', '<p>Dice breaking even high roller. Payoff score dealer baccarat! Insurance the strip odds the mirage shuffle the chandelier rack pass. New york, new york capriotti\'s double down dealer pot two pair pass spaghetti bowl! </p>\r\n<p>Blind card counting shops at crystals high roller draw margaritaville aria. Pass capriotti\'s stand. Straight margaritaville the mirage tease glitter gluch the venetian? The district sin city full house lounges the chapel of love flamingo hotel probability loose. </p>\r\n<p>Stratosphere shooter insurance bankroll aria dealer glitter gluch. Straight dice bankroll new york, new york treasure island; the district parlay comps price! Push the joint new york, new york two pair lock insurance pit the palms! Price hand lounges comps the joint bust? </p>\r\n<p>Flamingo hotel hand hard rock hotel bankroll naked city, spaghetti bowl the mirage pot exposure. Body english the strip hand dayclubs tao. Glitter gluch bars pit boss draw straight: shooter baccarat rack fruit loop? Chateau capriotti\'s parlay hard rock hotel cosmopolitan feeling lucky: stratosphere lock the joint royal flush! </p>', 'dice craps bets props strategies hardways yo eleven snake eyes boxcars', 'Published', 42),
(105, 51, 'Gluttony Greed Lust Sloth Wrath Envy Pride', 'pahrump', '2015-09-19 05:26:33', 'image8.png', '<p>Two pair town square pass pit boss the luxor chips? All in card counting dice? Tao high roller probability golden nugget exposure lounges house edge the pairs. Glitter gluch swim-up blackjack lock shuffle chateau hit unlv the chandelier. </p>\r\n<p>Push draw all in spaghetti bowl blind: the mgm grand hard rock hotel naked city comps? Double down score ante unlv! Shuffle card counting pass flamingo hotel sin city treasure island! Lax blackjack high roller the chapel of love fashion show mall unlv: miracle mile shops naked city bust full house. </p>\r\n<p>Chateau the strip stand double down vdara vegas givecamp dealer? Whale new york, new york stand ante sixth street pit, shuffle aria convention center price? The excalibur double down spaghetti bowl? Pit city center the joint fifth street baccarat vdara card counting miracle mile shops. </p>', 'deadly sins hell evil devil damnation', 'Published', 49),
(106, 73, 'Best Sushi Restaurant', 'robin', '2015-09-19 05:26:33', 'image11.png', '<p>Bar robusta mocha et foam aromatic aroma. Siphon sweet, blue mountain in wings viennese, single origin breve shop trifecta bar decaffeinated. That cup variety pumpkin spice americano macchiato body breve. Flavour cream robust dark, milk extraction barista caffeine medium.</p>\r\n<p>Body, frappuccino redeye, acerbic sweet pumpkin spice whipped rich caramelization. As affogato roast skinny grinder decaffeinated so plunger pot sugar and robust robusta. Iced blue mountain, mocha frappuccino, redeye irish decaffeinated affogato filter. Qui eu filter lungo dark steamed wings aged acerbic.</p>', 'sushi restaurant japanese food cuisine', 'Published', 48),
(107, 69, 'Crawfish Etoufee and Gumbo', 'robin', '2015-09-19 05:26:33', 'image14.png', 'Boucherie file beignet canaille beignet gumbo. Hot sauce levee boiled crawfish tasso farmer\'s market gulf shrimp yams Mardi Gras canaille etoufee. Bbq sac a lait pecan pie fais do do cher interstate King Cake boudin boiled crawfish. Farmer\'s market couillon Boudreaux sauce piquante coffee. Fauxcheaux gulf shrimp smoked sausage fais do do merci beaucoup envie merci beaucoup levee mirliton levee. Po-boy football andouille catahoula King Cake bayou bourre sac a lait Thibideaux catahoula. Pirogue etoufee bisque macque choux football gulf shrimp Acadiana. \r\n\r\nLagniappe turducken jambalaya crawfish cayenne sauce piquante barbed wire sauce piquante King Cake crawfish. Bonjour iced tea andouille gumbo catahoula football mirliton interstate. Pecan pie alligator jambalaya levee hunting Fauxcheaux fried catfish couillon canaille po-boy. Fried catfish andouille food sauce piquante andouille po-boy macque choux. Acadiana mirliton envie boucherie boucherie macque choux Lafayette. Sa fait chaud jambalaya gumbo bread pudding fried chicken. Hot sauce beignet fais do do food andouille bayou bread pudding iced tea fais do do macque choux. \r\n', 'louisiana new orleans cajun restaurant food', 'Published', 40),
(108, 74, 'Vegas Downtown Eats', 'robin', '2015-09-19 05:26:33', 'image15.png', '<p>Pot body english golden nugget sin city stand; feeling lucky the pairs city center house edge? Unlv blackjack sixth street capriotti\'s! Feeling lucky push the mgm grand? Draw tapped out royal flush the mirage the pairs feeling lucky; lock sixth street flamingo hotel fashion show mall! </p>\r\n<p>Draw vegas givecamp bars ante! Parlay house edge straight push? Shops at crystals probability draw body english mandalay bay; the pairs fold margaritaville blackjack. Glitter gluch the venetian parlay zappos straight rack! </p>\r\n<p>Body english fremont street loose bellagio bars! Swim-up blackjack the chandelier city center pit boss! Full house sin city house edge pit edge mandalay bay; vegas givecamp unlv bluff stand? Top of the world sixth street convention center fremont street blind mandalay bay? </p>\r\n<p>Two pair insurance pit the mgm grand card counting golden nugget? Blind margaritaville insurance the joint push hit score! Fifth street bust feeling lucky mandalay bay hand straight shops at crystals? Flamingo hotel lounges nightclubs top of the world cosmopolitan score miracle mile shops. </p>', 'vegas downtown restaurants food', 'Published', 43),
(111, 53, 'Switching from don\'t-come bets to come-bets', 'leonard', '2015-09-21 10:29:47', '', '<p>Hit fruit loop spaghetti bowl! Dice betting limits chateau golden nugget cosmopolitan the luxor caesar\'s palace! Comps blackjack bellagio unlv probability? Golden nugget rack fremont street hard rock hotel the venetian: dice breaking even baccarat price? </p>\r\n<p>Lax veer towers pass hit baccarat all in? Blackjack betting limits bankroll baccarat hand flush the venetian vegas givecamp! Exposure new york, new york all in shuffle city center bars feeling lucky convention center. Mandalay bay the pairs whale the strip pass all in, bellagio full house spaghetti bowl betting limits? </p>', 'craps dice strategies', 'Published', 5);

-- --------------------------------------------------------

--
-- Table structure for table `cms_sessions`
--

CREATE TABLE `cms_sessions` (
  `session_id` int(11) NOT NULL,
  `session` varchar(255) NOT NULL,
  `time` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `cms_sessions`
--

INSERT INTO `cms_sessions` (`session_id`, `session`, `time`) VALUES
(4, 'ou098ffhauv6l4g6o5gk4luis2', 1442481813),
(5, '31pps06iohav5p0tc24jj3bh15', 1442430937),
(6, 'i2gidon449fnvapds8j6smimj6', 1442514244),
(7, 'neo04hp0tqgkil4omop2k9hbp7', 1442521381),
(8, 'jg2odiutvq73knv7cd6226u7o0', 1442557870),
(9, '3amfnhkk37b31r38c2lrblhbb0', 1442545641),
(10, 'j8ttg0dl3f0ebh9s5apbd4hd80', 1442566730),
(11, '8mshoktjnb3dk6fp8u7qgvb9m3', 1442622866),
(12, 'bmd3k3ndfjr2vh5355b10bvb72', 1442625385),
(13, '290la5d6mtv2haegtc6ep1vpl4', 1442641506),
(14, 'v1ahsjldpo07f8jmao7mljo9h6', 1442642525),
(15, 'dl7th98b8vmvdb7snikdp74qc1', 1442644575),
(16, '1d3c8m1d7mc03tk92qah547jk5', 1442829018),
(17, '7au4dnllf0qvam71e28qsic7k1', 1442831622),
(18, '6pjud0b11lgjg2hi6ms9jtj3c3', 1442874851),
(19, 'cmcns60apgekf2a1vq2oj8k0k2', 1442875464),
(20, '47gho13l6gbdj2ok0ohhqo5od4', 1442885074),
(21, 'lnvigrhpb2gboen0ifq2v8f132', 1442901186),
(22, 'suf9lmhanikftmro6gaal0dbe0', 1442898402),
(23, 'n1fb34444gvci0kbcn9iue2em6', 1442907112),
(24, 'tg7omqje7c7lj6ukbsiq76mi4c', 1516913634),
(25, 'l4qt4l58rfe7o3aumhfijb6c3j', 1516911563);

-- --------------------------------------------------------

--
-- Table structure for table `cms_users`
--

CREATE TABLE `cms_users` (
  `user_id` int(3) NOT NULL,
  `user_uname` varchar(50) NOT NULL,
  `user_pass` varchar(255) NOT NULL,
  `user_fname` varchar(50) NOT NULL,
  `user_lname` varchar(50) NOT NULL,
  `user_email` varchar(100) NOT NULL,
  `user_image` varchar(50) NOT NULL DEFAULT 'default.png',
  `user_role` varchar(50) NOT NULL DEFAULT 'Subscriber',
  `user_status` varchar(50) NOT NULL DEFAULT 'Active',
  `user_date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `cms_users`
--

INSERT INTO `cms_users` (`user_id`, `user_uname`, `user_pass`, `user_fname`, `user_lname`, `user_email`, `user_image`, `user_role`, `user_status`, `user_date`) VALUES
(1, 'elvis', '$2y$12$op8mS/B2oQdGV3CA/kP4a.o1pWBIj7wIR9VgXd3XRgPYvb9ZAM6P6', 'Elvis', 'Impersonator', 'elvis@stuvwxyz.com', 'elvis.png', 'Administrator', 'Active', '2015-09-14 00:17:44'),
(3, 'chilin', '$2y$12$rIMfZX292fJ5jTLLftZvJ.Bzl6kheybEMcE.Z7yBNonA81OdBxDwq', 'Chi', 'Lin', 'chilin@stuvwxyz.com', 'elvis.png', 'Administrator', 'Active', '2015-09-14 00:18:48'),
(8, 'dicemaster', '$2y$12$D3A4Gvaw7uM5scJ72ZJgMOxNNAJXxw94ZStU2YRyrFzstuJmEaDaa', 'Johnny', 'Gambler', 'dicemaster@stuvwxyz.com', 'dicemaster.png', 'Subscriber', 'Active', '2015-09-15 14:29:16'),
(9, 'doctordice', '$2y$12$i41efFhJ4NSDl6IJsKatQO3XY78es2nKd/g0jJHmxPe5ZxRHoVvx2', 'Leonard', 'Benson', 'doctordice@stuvwxyz.com', 'doctordice.png', 'Subscriber', 'Active', '2015-09-15 14:32:28'),
(10, 'highroller', '$2y$12$X9xHeUFIVJ0G5r.3VDW4wO2loeNOvg.jN/02/y2.wPWkBavyBLMCi', 'High', 'Roller', 'highroller@stuvwxyz.com', 'highroller.png', 'Subscriber', 'Active', '2015-09-15 14:35:49'),
(11, 'casinoowner', '$2y$12$COZWyG6KtPMUTrOMfkwG2eSh37ODh2L/aGaG4HBOjkbFxv6yE3E/i', 'Steve', 'Something', 'casinoowner@stuvwxyz.com', 'casinoowner.png', 'Subscriber', 'Active', '2015-09-15 14:39:40'),
(13, 'partygirl', '$2y$12$URvjqefcJc/FnEEN/D.I1OevyvZThpZVqKYZ53a6WPM5amWR1QkwG', 'Party', 'Girl', 'partygirl@stuvwxyz.com', 'partygirl.png', 'Subscriber', 'Active', '2015-09-15 14:48:45'),
(14, 'pahrump', '$2y$12$0wOnccRZHTc8zfZv.vgOt.oFTj7xuuaTrpUdfaCQ7ctKoi32lql56', 'Jane', 'Doe', 'pahrump@stuvwxyz.com', 'pahrump.png', 'Subscriber', 'Active', '2015-09-15 14:51:49'),
(15, 'strategist', '$2y$12$HD1anN2YADIfemsVvSvO0eqBDSOZEGbGL.W9ukbJ99biF/7DnzWcq', 'John', 'Smith', 'strategist@stuvwxyz.com', 'strategist.png', 'Subscriber', 'Active', '2015-09-15 14:54:30'),
(19, 'samuel', '$2y$12$g8iUbuNwBq5nol9CEwnBUuCLZPeXD4JWmYuhHMjg0FfrZtCaPb3lC', 'Samuel', 'L.', 'samuel@stuvwxyz.com', 'samuel.png', 'Subscriber', 'Active', '2015-09-15 16:59:12'),
(20, 'blofeld', '$2y$12$qUFjsDAx857xf7eS5naVPO6oBohz5kXsC8SgN.vK1so1b/DCE6IB2', 'Ernst', 'Blofeld', 'blofeld@stuvwxyz.com', 'blofeld.png', 'Subscriber', 'Active', '2015-09-15 17:41:55'),
(26, 'robin', '$2y$12$NGoCRywMNHqwiwk8zJx03OekmtP.AgHAUU3oTVciFItt4zHfJL6q6', 'Robin', 'Lee', 'robin@stuvwxyz.com', 'robin.png', 'Subscriber', 'Active', '2015-09-16 19:39:45'),
(30, 'tiffany', '$2y$12$cW0RnnXJvfGqprGm5.haM.ZPGjzAU4QSpOWI0lVdSJjdcoLYp2dPa', 'Tiffany', 'Chang', 'tiffany@stuvwxyz.com', 'default.png', 'Subscriber', 'Active', '2015-09-17 18:25:50'),
(34, 'eleanor', '$2y$12$oC/kwcHtheddAdTg6ssdweeS0XD7dhac0CoQfLtN/XNzQvTOeGAHK', 'Eleanor', 'Aquitaine', 'eleanor@stuvwxyz.com', 'eleanor.png', 'Subscriber', 'Active', '2015-09-17 19:42:09'),
(38, 'test66', '$2y$12$SfB06i3yng9q5GA//t5LdOPiRpqjKv1ZWmi0mhAzX4TcCfXdFiB4O', 'Margaret', 'Anjou', 'test66@stuvwxyz.com', 'anjou.png', 'Subscriber', 'Active', '2015-09-17 23:10:12'),
(39, 'leonard', '$2y$12$7jYZCGG5qO/xH70dj2YYde1BL/acOBdJFvEI.KBKNxGSIc2hu/mvG', 'Leonard', 'B.', 'leonard@stuvwxyz.com', 'default.png', 'Subscriber', 'Active', '0000-00-00 00:00:00'),
(40, 'guest', '$2y$12$tGBin39xZEWZu0qMBKGsbufZiYxLkL3DY00N9z6IRIBg3hXoDZJDq', 'Guest', 'Guest', 'guest@stuvwxyz.com', 'default.png', 'Subscriber', 'Active', '0000-00-00 00:00:00');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cms_categories`
--
ALTER TABLE `cms_categories`
  ADD PRIMARY KEY (`cat_id`);

--
-- Indexes for table `cms_comments`
--
ALTER TABLE `cms_comments`
  ADD PRIMARY KEY (`comment_id`),
  ADD KEY `comment_post_id` (`comment_post_id`);

--
-- Indexes for table `cms_posts`
--
ALTER TABLE `cms_posts`
  ADD PRIMARY KEY (`post_id`),
  ADD KEY `post_cat_id` (`post_cat_id`),
  ADD KEY `post_author` (`post_author`);

--
-- Indexes for table `cms_sessions`
--
ALTER TABLE `cms_sessions`
  ADD PRIMARY KEY (`session_id`);

--
-- Indexes for table `cms_users`
--
ALTER TABLE `cms_users`
  ADD PRIMARY KEY (`user_id`),
  ADD UNIQUE KEY `user_uname` (`user_uname`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cms_categories`
--
ALTER TABLE `cms_categories`
  MODIFY `cat_id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=75;

--
-- AUTO_INCREMENT for table `cms_comments`
--
ALTER TABLE `cms_comments`
  MODIFY `comment_id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=84;

--
-- AUTO_INCREMENT for table `cms_posts`
--
ALTER TABLE `cms_posts`
  MODIFY `post_id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=112;

--
-- AUTO_INCREMENT for table `cms_sessions`
--
ALTER TABLE `cms_sessions`
  MODIFY `session_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

--
-- AUTO_INCREMENT for table `cms_users`
--
ALTER TABLE `cms_users`
  MODIFY `user_id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `cms_comments`
--
ALTER TABLE `cms_comments`
  ADD CONSTRAINT `fk_comments_posts` FOREIGN KEY (`comment_post_id`) REFERENCES `cms_posts` (`post_id`);

--
-- Constraints for table `cms_posts`
--
ALTER TABLE `cms_posts`
  ADD CONSTRAINT `fk_posts_cats` FOREIGN KEY (`post_cat_id`) REFERENCES `cms_categories` (`cat_id`),
  ADD CONSTRAINT `fk_posts_users` FOREIGN KEY (`post_author`) REFERENCES `cms_users` (`user_uname`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
